"""
LaserForge Professional SVG Exporter.
Exports LaserForge canvas entities to standard, clean SVG XML documents
with millimeter dimensions, LightBurn layer groupings, stroke colors,
and optional embedded raster images for Print & Cut.
"""

from typing import List, Tuple, Dict, Optional
import os
import io
import base64
import math
from PIL import Image

from laserforge.config import LAYER_PALETTE, DEFAULT_BED_WIDTH_MM, DEFAULT_BED_HEIGHT_MM
from laserforge.core.models import (
    LaserEntity, PathEntity, RectEntity, CircleEntity, LineEntity, TextEntity, ImageEntity
)


class SVGExporter:
    """Exports LaserForge entities to W3C-compliant SVG format."""

    @staticmethod
    def export_svg_string(
        entities: List[LaserEntity],
        bed_width_mm: float = DEFAULT_BED_WIDTH_MM,
        bed_height_mm: float = DEFAULT_BED_HEIGHT_MM,
        crop_to_content: bool = True,
        margin_mm: float = 5.0
    ) -> str:
        """
        Generates clean SVG XML string from a list of LaserEntities.
        """
        if not entities:
            return f"""<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="{bed_width_mm:.2f}mm" height="{bed_height_mm:.2f}mm" viewBox="0 0 {bed_width_mm:.2f} {bed_height_mm:.2f}">
</svg>"""

        layer_map = {lyr["id"]: lyr for lyr in LAYER_PALETTE}

        # Calculate bounding box
        if crop_to_content:
            min_x = min(e.get_bounds()[0] for e in entities) - margin_mm
            min_y = min(e.get_bounds()[1] for e in entities) - margin_mm
            max_x = max(e.get_bounds()[2] for e in entities) + margin_mm
            max_y = max(e.get_bounds()[3] for e in entities) + margin_mm
            min_x = max(0.0, min_x)
            min_y = max(0.0, min_y)
            doc_w = max_x - min_x
            doc_h = max_y - min_y
            vb_min_x, vb_min_y = min_x, min_y
        else:
            vb_min_x, vb_min_y = 0.0, 0.0
            doc_w = bed_width_mm
            doc_h = bed_height_mm

        # Group entities by layer
        layer_groups: Dict[int, List[LaserEntity]] = {}
        for e in entities:
            layer_groups.setdefault(e.layer_id, []).append(e)

        xml_lines = [
            '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
            f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"',
            f'     width="{doc_w:.2f}mm" height="{doc_h:.2f}mm"',
            f'     viewBox="{vb_min_x:.2f} {vb_min_y:.2f} {doc_w:.2f} {doc_h:.2f}">',
            '  <title>LaserForge Design Export</title>',
            '  <desc>Generated by LaserForge CAD/CAM</desc>'
        ]

        # Sort layers ascending
        for lyr_id in sorted(layer_groups.keys()):
            lyr_meta = layer_map.get(lyr_id, {"name": f"C{lyr_id:02d}", "color": "#FF2A2A", "label": f"Layer {lyr_id}"})
            color = lyr_meta["color"]
            lyr_name = f"{lyr_meta['name']}_{lyr_meta.get('label', '')}".replace(" ", "_")

            xml_lines.append(f'  <g id="{lyr_name}" stroke="{color}" fill="none">')

            for e in layer_groups[lyr_id]:
                if isinstance(e, LineEntity):
                    xml_lines.append(
                        f'    <line x1="{e.x:.3f}" y1="{e.y:.3f}" x2="{e.x2:.3f}" y2="{e.y2:.3f}" stroke="{color}" stroke-width="0.2" />'
                    )

                elif isinstance(e, CircleEntity):
                    if abs(e.radius_x - e.radius_y) < 1e-3:
                        xml_lines.append(
                            f'    <circle cx="{e.x:.3f}" cy="{e.y:.3f}" r="{e.radius_x:.3f}" stroke="{color}" stroke-width="0.2" />'
                        )
                    else:
                        xml_lines.append(
                            f'    <ellipse cx="{e.x:.3f}" cy="{e.y:.3f}" rx="{e.radius_x:.3f}" ry="{e.radius_y:.3f}" stroke="{color}" stroke-width="0.2" />'
                        )

                elif isinstance(e, RectEntity):
                    rx_attr = f' rx="{e.corner_radius:.3f}" ry="{e.corner_radius:.3f}"' if e.corner_radius > 0 else ""
                    xml_lines.append(
                        f'    <rect x="{e.x:.3f}" y="{e.y:.3f}" width="{e.width:.3f}" height="{e.height:.3f}"{rx_attr} stroke="{color}" stroke-width="0.2" />'
                    )

                elif isinstance(e, PathEntity):
                    d_parts = []
                    for c in e.contours:
                        if len(c) < 2:
                            continue
                        d_sub = [f"M {e.x + c[0][0]:.3f} {e.y + c[0][1]:.3f}"]
                        for pt in c[1:]:
                            d_sub.append(f"L {e.x + pt[0]:.3f} {e.y + pt[1]:.3f}")
                        if e.closed:
                            d_sub.append("Z")
                        d_parts.append(" ".join(d_sub))
                    if d_parts:
                        full_d = " ".join(d_parts)
                        xml_lines.append(
                            f'    <path d="{full_d}" stroke="{color}" stroke-width="0.2" fill="none" fill-rule="evenodd" />'
                        )

                elif isinstance(e, TextEntity):
                    font_style = f'font-family="{e.font_family}" font-size="{e.font_size:.2f}px"'
                    if e.bold: font_style += ' font-weight="bold"'
                    if e.italic: font_style += ' font-style="italic"'
                    baseline_y = e.y + e.height * 0.8
                    fill = color if e.fill_mode == "Fill" else "none"
                    stroke = color if e.fill_mode != "Fill" else "none"
                    xml_lines.append(
                        f'    <text x="{e.x:.3f}" y="{baseline_y:.3f}" {font_style} fill="{fill}" stroke="{stroke}">{e.text}</text>'
                    )

                elif isinstance(e, ImageEntity):
                    if e.image_path and os.path.exists(e.image_path):
                        try:
                            with Image.open(e.image_path) as pil_img:
                                buf = io.BytesIO()
                                pil_img.save(buf, format="PNG")
                                b64 = base64.b64encode(buf.getvalue()).decode("utf-8")
                                xml_lines.append(
                                    f'    <image x="{e.x:.3f}" y="{e.y:.3f}" width="{e.width:.3f}" height="{e.height:.3f}" '
                                    f'href="data:image/png;base64,{b64}" />'
                                )
                        except Exception:
                            pass

            xml_lines.append('  </g>')

        xml_lines.append('</svg>')
        return "\n".join(xml_lines)

    @staticmethod
    def export_svg_file(
        entities: List[LaserEntity],
        filepath: str,
        bed_width_mm: float = DEFAULT_BED_WIDTH_MM,
        bed_height_mm: float = DEFAULT_BED_HEIGHT_MM,
        crop_to_content: bool = True
    ) -> bool:
        """Exports entities to an SVG file on disk."""
        svg_content = SVGExporter.export_svg_string(
            entities,
            bed_width_mm=bed_width_mm,
            bed_height_mm=bed_height_mm,
            crop_to_content=crop_to_content
        )
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(svg_content)
        return True
