"""
LaserForge Menu Builder.
Constructs the main menu bar from the ActionRegistry.
Keeps menu layout separate from action definition and business logic.
"""
from PyQt6.QtWidgets import QMainWindow, QMenuBar
from laserforge.ui.action_registry import ActionRegistry

class MenuBuilder:
    """Builds the main menu bar for LaserForge MainWindow."""

    def __init__(self, window: QMainWindow, actions: ActionRegistry):
        self._window = window
        self._actions = actions

    def build(self) -> None:
        """Creates and attaches the full menu bar to the window."""
        mb = self._window.menuBar()
        self._build_file_menu(mb)
        self._build_edit_menu(mb)
        self._build_laser_menu(mb)
        self._build_tools_menu(mb)
        self._build_view_menu(mb)
        self._build_arrange_menu(mb)
        self._build_help_menu(mb)

    def _build_file_menu(self, mb):
        a = self._actions
        m = mb.addMenu('&File')
        m.addAction(a.new)
        m.addAction(a.open)
        self._window.menu_recent = m.addMenu("Open &Recent")
        self._window._update_recent_menu()
        m.addAction(a.save)
        m.addAction(a.save_as)
        m.addAction(a.bundle_packager)
        m.addSeparator()
        m.addAction(a.import_svg)
        m.addAction(a.import_dxf)
        m.addAction(a.import_lbrn)
        m.addAction(a.import_img)
        m.addAction(a.trace_image)
        m.addAction(a.image_cutout)
        m.addSeparator()
        m.addAction(a.export_gcode)
        m.addAction(a.export_svg)
        m.addAction(a.export_dxf)
        m.addAction(a.export_lbrn)
        m.addSeparator()
        m.addAction(a.exit)

    def _build_edit_menu(self, mb):
        a = self._actions
        m = mb.addMenu('&Edit')
        m.addAction(a.undo)
        m.addAction(a.redo)
        m.addSeparator()
        m.addAction(a.select_all)
        m.addAction(a.duplicate)
        m.addAction(a.delete)
        m.addSeparator()
        m.addAction(a.flip_h)
        m.addAction(a.flip_v)
        m.addSeparator()
        m_bool = m.addMenu("📐 Vector Booleans (CSG)")
        m_bool.addAction(a.weld)
        m_bool.addAction(a.subtract)
        m_bool.addAction(a.intersect)
        m_bool.addAction(a.xor)
        m.addAction(a.weld)
        m.addAction(a.subtract)
        m.addAction(a.intersect)
        m.addAction(a.xor)
        m.addSeparator()
        m.addAction(a.add_to_art_library)
        m.addAction(a.convert_to_path)

    def _build_laser_menu(self, mb):
        a = self._actions
        m = mb.addMenu('&Laser')
        m.addAction(a.auto_connect)
        m.addSeparator()
        m.addAction(a.preview)
        m.addAction(a.job_estimator)
        m.addAction(a.validate_gcode)
        m.addAction(a.frame)
        m.addAction(a.burn_perimeter)
        m.addAction(a.start_job)
        m.addAction(a.resume_job)
        m.addAction(a.pause_job)
        m.addAction(a.stop_job)
        m.addSeparator()
        m.addAction(a.align_workpiece)
        m.addAction(a.rotary)
        m.addAction(a.material_lib)
        m.addAction(a.material_test_studio)
        m.addAction(a.ruida_studio)
        m.addAction(a.web_pendant)
        m.addSeparator()
        m.addAction(a.auto_calibrate)
        m.addAction(a.camera_wizard)
        m.addAction(a.camera_update)
        m.addAction(a.camera_fine_tune)
        m.addAction(a.camera_toggle)
        m.addAction(a.multi_camera)
        m.addSeparator()
        m.addAction(a.home)
        m.addAction(a.unlock)
        m.addSeparator()
        m.addAction(a.workbed_setup)
        m.addAction(a.settings)

    def _build_tools_menu(self, mb):
        a = self._actions
        m = mb.addMenu('&Tools')
        m.addAction(a.workbed_setup)
        m.addAction(a.auto_calibrate)
        m.addAction(a.camera_wizard)
        m.addAction(a.camera_update)
        m.addAction(a.camera_fine_tune)
        m.addAction(a.multi_camera)
        m.addSeparator()
        m.addAction(a.job_estimator)
        m.addAction(a.photo_studio)
        m.addAction(a.templates_studio)
        m.addAction(a.shapes_lib)
        m.addAction(a.offset_border)
        m.addAction(a.grid_array)
        m.addAction(a.common_line)
        m.addAction(a.variable_text)
        m.addSeparator()
        m.addAction(a.curved_text)
        m.addAction(a.serial_gen)
        m.addSeparator()
        m.addAction(a.business_card)
        m.addAction(a.barcode_studio)
        m.addAction(a.sdxl_turbo)
        m.addAction(a.ai_assistant)
        m.addAction(a.crop_image)
        m.addAction(a.gen_qr)
        m.addAction(a.trace_image)
        m.addAction(a.image_cutout)
        m.addAction(a.directional_hatch)
        m.addAction(a.holding_tabs)
        m.addAction(a.print_and_cut)
        m.addAction(a.nesting)
        m.addAction(a.rotary)
        m.addAction(a.box_generator)
        m.addAction(a.living_hinge)
        m.addAction(a.single_line_text)
        m.addAction(a.material_test_studio)
        m.addAction(a.relief_studio)
        m.addAction(a.galvo_studio)
        m.addAction(a.ruida_studio)
        m.addAction(a.web_pendant)
        m.addAction(a.bundle_packager)
        m.addAction(a.art_library)
        m.addAction(a.z_probe)
        m.addAction(a.surface_wrap)
        m.addSeparator()
        m.addAction(a.material_lib)
        m.addAction(a.test_matrix)
        m.addAction(a.kerf_test)
        m.addAction(a.align_workpiece)
        m.addAction(a.burn_perimeter)
        m.addAction(a.alignment_marks_studio)
        m.addSeparator()
        m.addAction(a.preview)
        m.addAction(a.zoom_fit)

    def _build_view_menu(self, mb):
        a = self._actions
        m = mb.addMenu('&View')
        m.addAction(a.zoom_fit)
        m.addSeparator()
        m.addAction(a.snap_grid)
        m.addAction(a.toggle_guides)
        m.addAction(a.clear_guides)
        m.addSeparator()
        self._window.menu_view_docks = m.addMenu("📁 Docks & Panels")

    def _build_arrange_menu(self, mb):
        a = self._actions
        m = mb.addMenu('&Arrange')
        m.addAction(a.bed_center)
        m.addAction(a.center_in_parent)
        m.addAction(a.common_line)
        m.addSeparator()
        m.addAction(a.align_left)
        m.addAction(a.align_center_x)
        m.addAction(a.align_right)
        m.addAction(a.align_top)
        m.addAction(a.align_center_y)
        m.addAction(a.align_bottom)
        m.addSeparator()
        m.addAction(a.distribute_h)
        m.addAction(a.distribute_v)
        m.addSeparator()
        m.addAction(a.flip_h)
        m.addAction(a.flip_v)
        m.addSeparator()
        m.addAction(a.grid_array)
        m.addAction(a.offset_border)
        m.addSeparator()
        m.addAction(a.corner_l_marks)
        m.addAction(a.center_cross)
        m.addAction(a.alignment_marks_studio)

    def _build_help_menu(self, mb):
        a = self._actions
        m = mb.addMenu('&Help')
        m.addAction(a.user_guide)
        m.addAction(a.interactive_tutorial)
        m.addAction(a.send_feedback)
        m.addSeparator()
        m.addAction(a.license)
        m.addAction(a.check_updates)
        m.addSeparator()
        # About requires local QAction, let's keep it simple
        from PyQt6.QtGui import QAction
        act_about = QAction("About LaserForge...", self._window)
        act_about.triggered.connect(self._window._show_about)
        m.addAction(act_about)
