"""
LaserForge Example Plugin: G-Code Header & Production Logger
Demonstrates:
- Hooking G-code generation with a custom post-processor (adds safety header & metadata)
- Subscribing to job lifecycle events (start & completion logging)
"""

import time
from typing import Dict, Any, Optional, Callable
from laserforge.core.plugin_api import LaserForgePlugin, PluginMetadata


class GCodeHeaderPlugin(LaserForgePlugin):
    metadata = PluginMetadata(
        name="GCodeHeaderLogger",
        version="1.1.0",
        author="LaserForge Core Team",
        description="Injects production metadata header into emitted G-code and logs job execution."
    )

    def on_load(self, app_context: Dict[str, Any]) -> None:
        self.settings = app_context.get("settings")
        self.layer_manager = app_context.get("layer_manager")
        print(f"[{self.metadata.name}] Successfully loaded into LaserForge.")

    def on_unload(self) -> None:
        print(f"[{self.metadata.name}] Unloaded.")

    def register_gcode_postprocessor(self) -> Optional[Callable[[str], str]]:
        def _add_production_header(gcode: str) -> str:
            ts = time.strftime("%Y-%m-%d %H:%M:%S")
            header = [
                "; ========================================================",
                f"; GENERATED BY LASERFORGE PRO WITH {self.metadata.name.upper()}",
                f"; Timestamp: {ts}",
                "; Operator Safety Checklist: Safety glasses on, exhaust running",
                "; ========================================================",
                ""
            ]
            return "\n".join(header) + gcode

        return _add_production_header

    def on_job_start(self, gcode: str, estimated_time_sec: float) -> None:
        print(f"[{self.metadata.name}] Job started! Estimated time: {estimated_time_sec:.1f}s, G-code lines: {len(gcode.splitlines())}")

    def on_job_complete(self, duration_sec: float, was_aborted: bool) -> None:
        status = "ABORTED" if was_aborted else "COMPLETED"
        print(f"[{self.metadata.name}] Job {status} in {duration_sec:.1f}s.")


PLUGIN_CLASS = GCodeHeaderPlugin
